export  const rosterList = [
    {
        key: "1",
        name: "DIENANDT",
        headPara: "Dienandt is a 17 year old producer from the Netherlands. His musical journey started at a very young age of 6 years old, getting piano lessons by his grandmother.",
        bodyPara: "At the start of his electronic music career, he was just learning how to use the still unfamiliar program, unconsciously developing a great passion for making music.",
        endPara: "Dienandt quickly got introduced to hard-hitting genres such as Bass Trap and Hard Trap, which he fell in love with. After more than a year of producing Bass Trap, Dienandt found his best-suited genre, Wave music. This much calmer type of music was a new experience for him, but after more than a year of hard work, he managed to create his own, unique sound in this genre.",
        youtube: "https://www.youtube.com/channel/UCW4AofArqJDLJW3X28d92kQ",
        soundcloud: "https://soundcloud.com/dienandt",
        spotify: "https://open.spotify.com/artist/0wL0vK7kJwdEFecQpTDceL",
        spotifyEmbed: "https://open.spotify.com/embed/artist/0wL0vK7kJwdEFecQpTDceL?utm_source=generator&amp;theme=0",        
    },
    {
        key: "2",
        name: "IKRAN",
        headPara: "Ikran, a guy from the UK, has been producing music since 2018.",
        bodyPara: "First, he started producing on a free software called LMMS, which is similar to FL studio, but inferior. Since it was less popular, there were very little tutorials on how to use LMMS, so he spent a year figuring it out, until he finally got FL Studio and started to really improve. ",
        endPara: "Like many producers, he began by making bad trap beats. he kept this up for a while until he thought he was good enough to publicise. And so he started his account called 'ikran'.",
        youtube: "https://www.youtube.com/channel/UC18JB2hjh8TA2ezitrsi7eA?view_as=subscriber",
        soundcloud: "https://soundcloud.com/ikranx",
        spotify: "https://open.spotify.com/artist/4yRSKRqdVNudn2lG5OZmnF",
        spotifyEmbed: "https://open.spotify.com/embed/artist/4yRSKRqdVNudn2lG5OZmnF?utm_source=generator&theme=0",
    },
    {
        key: "3",
        name: "MELEJEND",
        headPara: "Melejend, which name is Mark - young music producer from cold Siberia.",
        bodyPara: "He started making music in the summer of 2018. He wrote a lot of bad Trap tracks and couldn't think that he could achieve what he has now. He was very inspired by the producer from Romania, REALM. He’s very thankful for him and his tracks, because it motivated him to try his hand at music. He became an unknown Trap producer, but now his music and himself have changed. He began to like Wave, and decided to continue his musical activity in this genre. Now he’s inspired by hyperforms, FATE, iwilldiehere, Russian artists (PHARAOH, Markul, Midix and etc.), Russian Postpunk and longing for grey soviet panel houses. He will still release Trap tracks, but only on labels or collaborators profiles.",
        endPara: "So far, he’s still looking for his unique style, but he’s sure he’ll find it very soon.",
        youtube: "https://www.youtube.com/channel/UC1uLMoV1HQwxEIyQ6fEsidg",
        soundcloud: "https://soundcloud.com/melejend",
        spotify: "https://open.spotify.com/artist/7BYU4nM63yAWbKJigG3SXG",
        spotifyEmbed: "https://open.spotify.com/embed/artist/7BYU4nM63yAWbKJigG3SXG?utm_source=generator",
    },
    {
        key: "4",
        name: "RAZUMI",
        headPara: "This is razumi, a producer from the USA.",
        bodyPara: "He started “producing” in 2016 using Garageband, although he did not try to make actually good music. He started taking producing seriously starting in 2019. I had knowledge of music theory from taking piano lessons, but did not know anything about how production worked. It took a long time to get to an adequate level for him, but it was definitely worth the effort in the end.",
        endPara: "He started off making shitty Trap beats, and slowly improved at making them, until he got bored of them, and thought that bass trap was cool. He was really bad at it though, and the genre was also slowly dying anyways, so he looked for something new to try, and found Wave. It was something he could actually make well and had fun making, so he decided to stick with it, and he’s glad he did in the end.",
        youtube: "https://www.youtube.com/c/razumi1550",
        soundcloud: "https://soundcloud.com/razumi1550",
        spotify: "https://open.spotify.com/artist/2TpjnxhJtYMGouLpbOfQx1?si=pydIrF5NSVu9NMDAcMeHCg&nd=1",
        spotifyEmbed: "https://open.spotify.com/embed/artist/2TpjnxhJtYMGouLpbOfQx1?utm_source=generator&theme=0",
    },
    {
        key: "5",
        name: "SAPPHYRE",
        headPara: "Introducing Sebastian, also known as sapphyre. He chose this name because google wouldn't find him if his name was sapphire.",
        bodyPara: "On the 23rd of February, 2020, he started producing. He was getting really bored during lockdown due to the Corona virus, and couldn't develop his skills in other hobbies like graphic design and video editing. He decided to play with FL Studio, besides, that was the only software his computer could handle back then. He makes phonk, inspired by other producers like LXST CXNTURY, BLESSED MANE,  ÆSTRAL, or STAHL, though his tracks have more ambience flowing through them, that's why he called it wave/phonk.",
        endPara: "",
        youtube: "https://www.youtube.com/c/sapphyre",
        soundcloud: "https://soundcloud.com/sxpphyre",
        spotify: "https://open.spotify.com/artist/5nqa17OYrgbn9JX5ra4EgS?si=swGE0L6GQbewFA8Tzqlv5w&nd=1",
        spotifyEmbed: "https://open.spotify.com/embed/artist/5nqa17OYrgbn9JX5ra4EgS?utm_source=generator",
    },
    {
        key: "6",
        name: "OCLUSE",
        headPara: "Emerging from the dark corners of the soundcloud underground trap & wave scene, West-Europe based artist Ocluse combines melancholic, dreamy ambient soundscapes with bass that is equally as enchanting as it is ominous.",
        bodyPara: "Growing up in a small town, Ocluse has been surrounded by various forms of art for as long as they can remember, including music. This caused them to partake in various musical activities at a young age, such as singing in a choir & playing instruments in multiple rockbands.",
        endPara: "Heavily inspired by their friends & artists such as Fifty Grand, Lil Peep & Zaya, Ocluse is looking forward to make his sound even more pristine & unique in the future.",
        youtube: "https://www.youtube.com/channel/UCuhO81_8IpbE8yArC8gzO9A",
        soundcloud: "https://soundcloud.com/ocluse",
        spotify: "https://open.spotify.com/artist/6LEy89N3kZMC7QWSwpeZfg?si=THPM18TnR3qLWpRln-haBA&nd=1",
        spotifyEmbed: "https://open.spotify.com/embed/artist/6LEy89N3kZMC7QWSwpeZfg?utm_source=generator",
    },
    {
        key: "7",
        name: "EVADE",
        headPara: "Here’s evade, a young producer from the United States. You might also know him by his old name, Descry.",
        bodyPara: "Some background info, He has played piano for 7-8 years, he’s also in the school band and drumline. He started getting into production in 2017, however his DAW was a notation software called Musescore. That means that it was meant for sheet music. He creatively used the lack of good sounding instruments to start an “EDM scene” on the website, and many of his friends there have now gotten into real production. He realized that he needed to leave that and get a real DAW, so he bought FL Studio. He made mostly bass trap and a little bit of EDM under the names nxtlvl and Descry. On his Descry soundcloud profile, he got over 60k plays. He then discovered wave music, and he wanted a way to separate that from my bass trap music, so he changed his name to evade. He really got into hardwave at first, but he also makes future garage and ambient. He does have some bass house, hybrid trap, and rap beat projects laying around too. His style is his versatility and not just one sound.",
        endPara: "He’s really looking forward to become bigger, and he thinks he has the potential to be one of the top artists in the wave community in the next 5-10 years.",
        youtube: "https://www.youtube.com/channel/UCN1pMFs02eJFbO0-XxY7gtw/featured",
        soundcloud: "https://soundcloud.com/evadewave",
        spotify: "https://open.spotify.com/track/2MdsGaWbAnDIvLDLvO3Mt1?si=52fb7d7eac244621",
        spotifyEmbed: "https://open.spotify.com/embed/track/2MdsGaWbAnDIvLDLvO3Mt1?utm_source=generator",
    }

]